/****** Script for SelectTopNRows command from SSMS  ******/
/* SELECT TOP(1000)[TesterID]
   
    
    
FROM[TokaySQL].[dbo].[Technicians] */

export class Technicians {
         Status: number;
         FirstName: string;
         LastName: string;
         Address1: string;
         Address2: string;
         City: string;
         State: string;
         Zip: string;
         Phone: string;
         Fax: string;
         CntyLicNum: string;
         TestCertified: string;
         SurvCertified: string;
         InstCertified: number;
         TestCertNum: string;
         SurvCertNum: string;
         InstCertNum: string;
         ShowOnList: boolean;
         TestCertExp: string;
         SurvCertExp: string;
         InstCertExp: string;
         Fee: string;
         FeePaid: string;
         Comments: string;
         DateStamp: string;
         UID: number;
         COLICENSE: string;
         REPCERTIFIED: string;
         CNTRYLICex: string;
         CITYLICNUM: string;
         LICEXPDATE: string;
         CERTDATE: string;
         CERTAGCY: string;
         PLUMEXPIR: string;
         PLUMNUM: string;
         LANDEXPIR: string;
         LANDNUM: string;
         FIREEXPIR: string;
         FIRENUM: string;
         INSURANCE: string;
         POLICY: number;
         LIABILITY: string;
         INSUREXP: string;
         INSURAGT: string;
         INSURPHO: string;
         AllDataSets: string;
         Init: number;
         Email: string;
         Cell: string;
         UDF1: string;
         RepCertNum: string;
         RepCertExp: string;
         SurvCertAgcy: string;
         InstCertAgcy: string;
         RepCertAgcy: string;
         SurvCertDate: string;
         InstCertDate: string;
         RepCertDate: string;
         TestCertNum2: string;
         TestCertExp2: string;
         CertAgcy2: string;
         CertDate2: string;
         SurvCertNum2: string;
         SurvCertExp2: string;
         SurvCertAgcy2: string;
         SurvCertDate2: string;
         InstCertNum2: string;
         InstCertExp2: string;
         InstCertAgcy2: string;
         InstCertDate2: string;
         RepCertNum2: string;
         RepCertExp2: string;
         RepCertAgcy2: string;
         RepCertDate2: string;
         CityCheck: string;
         CountyCheck: string;
         PlumberCheck: string;
         LandScapeCheck: string;
         FireCheck: string;
         ConfinedCheck: string;
         ConfinedLicNum: string;
         ConfinedLicExp: string;
         LastLetter: string;
         LastLetterName: string;
         TesterUserID: string;
         Password: string;
         LastUpdate: string;
         LastUpdateID: number;
         LastUpdateBy: string;
         WebStatus: string;
         Contact: string;

         constructor(technicians) {
           {
             this.Status = technicians.Status;
             this.FirstName = technicians.FirstName;
             this.LastName = technicians.LastName;
             this.Address1 = technicians.Address1;
             this.Address2 = technicians.Address2;
             this.City = technicians.City;
             this.State = technicians.State;
             this.Zip = technicians.Zip;
             this.Phone = technicians.Phone;
             this.Fax = technicians.Fax;
             this.TestCertified = technicians.TestCertified;
             this.SurvCertified = technicians.SurvCertified;
             this.InstCertified = technicians.InstCertified;
             this.TestCertNum = technicians.TestCertNum;
             this.SurvCertNum = technicians.SurvCertNum;
             this.InstCertNum = technicians.InstCertNum;
             this.TestCertExp = technicians.TestCertExp;
             this.SurvCertExp = technicians.SurvCertExp;
             this.InstCertExp = technicians.InstCertExp;
             this.Email = technicians.Email;
             this.Cell = technicians.Cell;
             this.UDF1 = technicians.UDF1;
             this.Fee = technicians.Fee;
             this.FeePaid = technicians.FeePaid;
             this.Comments = technicians.Comments;
             this.DateStamp = technicians.County_Expire;
             this.UID = technicians.UID;
             this.COLICENSE = technicians.COLICENSE;
             this.REPCERTIFIED = technicians.REPCERTIFIED;
             this.CNTRYLICex = technicians.CNTRYLICex;
             this.CITYLICNUM = technicians.CITYLICNUM;
             this.LICEXPDATE = technicians.LICEXPDATE;
             this.CERTDATE = technicians.CERTDATE;
             this.CERTAGCY = technicians.CERTAGCY;
             this.PLUMNUM = technicians.PLUMNUM;
             this.PLUMEXPIR = technicians.PLUMEXPIR;
             this.LANDEXPIR = technicians.LANDEXPIR;
             this.LANDNUM = technicians.LANDNUM;
             this.FIREEXPIR = technicians.FIREEXPIR;
             this.FIRENUM = technicians.FIRENUM;
             this.UID = technicians.UID;
             this.INSURANCE = technicians.INSURANCE;
             this.POLICY = technicians.POLICY;
             this.LIABILITY = technicians.LIABILITY;
             this.INSUREXP = technicians.INSUREXP;
             this.INSURAGT = technicians.INSURAGT;
             this.INSURPHO = technicians.INSURPHO;
             this.AllDataSets = technicians.AllDataSets;
             this.Init = technicians.Init;
             this.RepCertNum = technicians.RepCertNum;
             this.RepCertExp = technicians.RepCertExp;
             this.SurvCertAgcy = technicians.SurvCertAgcy;
             this.InstCertAgcy = technicians.InstCertAgcy;
             this.SurvCertAgcy = technicians.SurvCertAgcy;
             this.RepCertAgcy = technicians.RepCertAgcy;
             this.SurvCertDate = technicians.SurvCertDate;
             this.InstCertDate = technicians.InstCertDate;
             this.RepCertDate = technicians.RepCertDate;
             this.TestCertNum2 = technicians.TestCertNum2;
             this.TestCertExp2 = technicians.TestCertExp2;
             this.CertAgcy2 = technicians.CertAgcy2;
             this.CertDate2 = technicians.CertDate2;
             this.SurvCertNum2 = technicians.SurvCertNum2;
             this.SurvCertExp2 = technicians.SurvCertExp2;
             this.SurvCertAgcy2 = technicians.SurvCertAgcy2;
             this.SurvCertDate2 = technicians.SurvCertDate2;
             this.InstCertNum2 = technicians.InstCertNum2;
             this.InstCertExp2 = technicians.InstCertExp2;
             this.InstCertAgcy2 = technicians.InstCertAgcy2;
             this.InstCertDate2 = technicians.InstCertDate2;
             this.RepCertNum2 = technicians.RepCertNum2;
             this.RepCertExp2 = technicians.RepCertExp2;
             this.RepCertAgcy2 = technicians.RepCertAgcy2;
             this.RepCertDate2 = technicians.RepCertDate2;
             this.ShowOnList = technicians.ShowOnList;
             this.CityCheck = technicians.CityCheck;
             this.CountyCheck = technicians.CountyCheck;
             this.PlumberCheck = technicians.PlumberCheck;
             this.LandScapeCheck = technicians.LandScapeCheck;
             this.FireCheck = technicians.FireCheck;
             this.ConfinedCheck = technicians.ConfinedCheck;
             this.ConfinedLicNum = technicians.ConfinedLicNum;
             this.ConfinedLicExp = technicians.ConfinedLicExp;
             this.LastLetter = technicians.LastLetter;
             this.LastLetterName = technicians.LastLetterName;
             this.TesterUserID = technicians.TesterUserID;
             this.Password = technicians.Password;
             this.LastUpdate = technicians.LastUpdate;
             this.LastUpdateID = technicians.LastUpdateID;
             this.LastUpdateBy = technicians.LastUpdateBy;
             this.WebStatus = technicians.WebStatus;
             this.Contact = technicians.Contact;
           }
         }

         toggleShowOnList() {
           this.ShowOnList = !this.ShowOnList;
         }
       }
