export class Summary {
    datasetid: number = 0;
    siteInfo: SiteInfo;
    companyNumber: string;
}

export class SiteInfo {
    siteInformation: SiteInformation;
    hazardList?: (HazardListEntity)[] | null;
}
export class SiteInformation {
    SiteID: number;
    ClientID: number;
    AccountNum: string;
    Contact: string;
    Company: string;
    Address: string;
    Address2?: null;
    City: string;
    State: string;
    zip: string;
    Phone: string;
    Ext?: null;
    Cell1?: null;
    Fax?: null;
    Email: string;
    LocationID: string;
    SiteType: string;
    SiteUse: string;
    TestMonth?: null;
    TestDay?: null;
    SurveyDue?: null;
    SurveyDue2?: null;
    SurveyFreq: string;
    CityLimits: boolean;
    UDF1: string;
    UDF2?: null;
    UDF3: string;
    LastSurvey?: null;
    LastLetter?: null;
    LastUpdate: string;
    LinkOn: boolean;
    Link?: null;
    LastLink: string;
    LinkCode: string;
    DateStamp: string;
    UID: string;
    LastUpdateBy: string;
    LastUpdateID: string;
    ShutOffDate?: null;
    sExtendDays?: null;
    sExtendedOn?: null;
    sNoticeDue1?: null;
    sNoticeSent1?: null;
    sNoticeSkip1: boolean;
    sNoticeDue2?: null;
    sNoticeSent2?: null;
    sNoticeSkip2: boolean;
    sNoticeDue3?: null;
    sNoticeSent3?: null;
    sNoticeSkip3: boolean;
    sNoticeDue4?: null;
    sNoticeSent4?: null;
    sNoticeSkip4: boolean;
    sShutOffDue?: null;
    sShutOffSent?: null;
    sShutOffSkip: boolean;
    sComplianceDate?: null;
    sComplianceSent?: null;
    LastLetterCode?: null;
    SurveyBy?: null;
    LastSurveyStatus?: null;
    UDF4?: null;
    UDF5: string;
    UDF6?: null;
    UDF7?: null;
    UDF8?: null;
    UDF9?: null;
    UDF10?: null;
    UDF11?: null;
    UDF12?: null;
    UDF13?: null;
    UDF14?: null;
    UDF15?: null;
    UDF16?: null;
    UDF17?: null;
    UDF18?: null;
    UDF19?: null;
    UDF20?: null;
    UDF21?: null;
    UDF22?: null;
    StreetName: string;
    LastName: string;
    StreetNo: number;
    HazCount: number;
    MCompany?: string;
    MAddress?: string;
    MCity?: string;
    MState?: string;
    MZip?: string;
    MPhone?: string;
    MEmail?: string;
}
export class HazardListEntity {
    Notes: string;
    HazID: number;
    SiteID: number;
    HazNum?: null;
    AccountNum?: string | null;
    Testable: boolean;
    HazardType?: string | null;
    HazardCat?: null;
    Priority?: string | null;
    Installed?: string | null;
    UDh1?: string | null;
    UDh2?: null;
    UDh3?: null;
    UDh4?: null;
    UDh5?: null;
    UDh6?: null;
    UDh7?: string | null;
    UDh8?: string | null;
    UDh9?: string | null;
    UDh10?: null;
    UDh11?: null;
    Location?: string | null;
    Location2?: string | null;
    SerialNum?: string | null;
    Meter?: string | null;
    MFG?: string | null;
    Model?: string | null;
    Type?: string | null;
    devSize?: string | null;
    Status?: string | null;
    TestDue?: string | null;
    InstallDue?: Date;
    installer?: string | null;
    InstalledDate?: Date;
    RemovedDate?: Date ;
    TestFreq?: number | null;
    LinkOn: boolean;
    Link?: string | null;
    LastLink?: string | null;
    LinkCode?: string | null;
    Recommend?: string | null;
    LineSize?: string | null;
    Orientation?: null;
    ServiceNo?: string | null;
    LastTest?: Date;
    LastLetter?: Date;
    LastUpdate?: string | null;
    DateStamp: string;
    UID: string;
    LastUpdateBy?: string | null;
    DevCode?: string | null;
    LastUpdateID?: string | null;
    NoticeDue1?: Date;
    NoticeSent1?: null;
    NoticeSkip1: boolean;
    NoticeDue2?: Date;
    NoticeSent2?: null;
    NoticeSkip2: boolean;
    NoticeDue3?: Date;
    NoticeSent3?: null;
    NoticeSkip3: boolean;
    NoticeDue4?: null;
    NoticeSent4?: null;
    NoticeSkip4: boolean;
    ExtendDays?: null;
    ExtendedOn?: null;
    iNoticeDue1?: null;
    iNoticeSent1?: null;
    iNoticeSkip1: boolean;
    iNoticeDue2?: null;
    iNoticeSent2?: null;
    iNoticeSkip2: boolean;
    iNoticeDue3?: null;
    iNoticeSent3?: null;
    iNoticeSkip3: boolean;
    iNoticeDue4?: null;
    iNoticeSent4?: null;
    iNoticeSkip4: boolean;
    iExtendDays?: null;
    iExtendOn?: null;
    LastLetterCode?: string | null;
    TestDue2?: null;
    TestBy?: null;
    InstallDue2?: null;
    InstallBy?: null;
    ShutOffDate?: Date;
    LastTestStatus?: string | null;
    UDH12?: null;
    UDH13?: string | null;
    UDH14?: null;
    UDH15?: null;
    UDH16?: null;
    UDH17?: null;
    UDH18?: null;
    UDH19?: null;
    UDH20?: null;
    UDH21?: null;
    UDH22?: null;
    UDH23?: null;
    UDH24?: null;
    UDH25?: null;
    UDH26?: null;
    UDH27?: null;
    UDH28?: null;
    UDH29?: null;
    UDH30?: null;
    SendNotices: boolean;
    Hide: boolean;
    HazardCatCode?: null;
    RecommendCode?: null;
    LeadFree: boolean;
    webFee?: number | null;
    LastTestBy?: string | null;
    LastTestCompany?: string | null;
    udh31?: null;
    udh32?: null;
    ByPass: boolean;
    AquaExternalID?: null;
    FireLine: boolean;
    SendToSite: boolean;
}

export class DevTest{
    TestID: number;
    HazID: number;
    SiteID: number;
    TestDue?: Date;
    NoticeDue1?: Date;
    NoticeSent1?: Date;
    NoticeSkip1: boolean;
    NoticeDue2?: Date;
    NoticeSent2?: Date;
    NoticeSkip2: boolean;
    NoticeDue3?: Date;
    NoticeSent3?: any;
    NoticeSkip3: boolean;
    NoticeDue4?: any;
    NoticeSent4?: any;
    NoticeSkip4: boolean;
    ExtendDays?: any;
    ExtendedOn?: any;
    iDate: Date;
    iPass: string;
    iType?: any;
    iTestBy: string;
    iTestKit?: any;
    I1AiPsi?: number;
    I1Ai: string;
    I2CvPsi?: number;
    I2Cv: string;
    IrPsi?: number;
    Irp?: any;
    IBuffer?: number;
    IHeld?: any;
    IShut?: any;
    Iex?: any;
    RepairDate?: any;
    Repair: boolean;
    RepairBy?: any;
    RepairType?: any;
    LinePsi: string;
    RepairCost: string;
    FailType?: any;
    Verified?: any;
    fDate?: any;
    fPass?: any;
    fType?: any;
    fTestBy?: any;
    fTestKit?: any;
    F1AiPsi?: number;
    F1Ai?: any;
    F2CvPsi?: number;
    F2Cv?: any;
    FrPsi?: number;
    Frp?: any;
    FBuffer?: number;
    Fheld?: any;
    FShut?: any;
    Fex?: any;
    UDT4?: any;
    UDT5?: any;
    UDT6?: any;
    UDT7?: any;
    UDT8: string;
    UDT9: string;
    LastDate?: any;
    DateStamp?: Date;
    UID: string;
    LastUpdate?: Date;
    LastUpdateID: string;
    iCompany: string;
    fCompany?: any;
    itestbyid?: number;
    ftestbyid?: any;
    iCertNum: string;
    fCertNum?: any;
    Proper: boolean;
    Shut2: boolean;
    Restore: boolean;
    RVExe: boolean;
    BackPres: boolean;
    iFull: boolean;
    fFull: boolean;
    MetRead?: any;
    LastUpdateBy: string;
    I3CVPSI?: any;
    I3CV?: any;
    F3CVPSI?: any;
    F3CV?: any;
}

